site_name: UTBULT DESIGN

plugins:
  - jinja2
  - translations:
      default_language: sv
      languages:
        en: english
        sv: svenska

markdown_extensions:
  - toc

hooks:
  - hooks/lang.py
  - hooks/category.py

theme:
  name: utbult-design
