site_name: UTBULT DESIGN

markdown_extensions:
  - toc
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - markdown_include.include:
      base_path: templates

extra_javascript:
  - ../misc/javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: utbult-design
  logo_light: img/UtbultDesign_White.svg
  logo_dark: img/UtbultDesign_Black.svg
  favicon: img/UtbultDesign_Small.png

plugins: 
  - awesome-pages


# nav:
#   - sv:
#     - Om Mig: sv/about_me.md
#     - Musik: Music/
#   - en:
#     - About Me: en/about_me.md

extra:
  alternate:
    - name: På Svenska
      link: /sv/
      lang: sv
    - name: In English
      link: /en/ 
      lang: en
